### ISSUE TITLE
CSS Bundling Edge Case

### ISSUE THREAD

**Issue by robmyers** [frozeman/meteor-build-client#21]
If there is no CSS in a new project (if the file minifies to nothing) and you run meteor-build-client then it raises an error:

```
meteor-build-client ../test-meteor --path ''
Bundling Meteor app...
Generating the index.html...
path.js:488
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Object.module.exports.addIndexFile (/usr/lib/node_modules/meteor-build-client/meteor.js:121:48)
    at /usr/lib/node_modules/meteor-build-client/main.js:79:20
    at null._onTimeout (/usr/lib/node_modules/meteor-build-client/queue.js:41:11)
    at Timer.listOnTimeout (timers.js:119:15)
```

I know this is ridiculously obscure, but it's possible if e.g. you are just trying out the system for the first time with a newly generated empty project.

**Comment by frozeman** [comment]
Could you try if you get the error again with the latest version 0.2.1?

**Comment by robmyers** [comment]
I just updated to 0.2.2, which doesn't give the error.
